### ISSUE TITLE
Rename `core` module to `api`

### ISSUE THREAD

**Issue by joshuasing** [ChameleonFramework/Chameleon#111]
I think it would be a good idea to rename the `core` module to `api` and the package `dev.hypera.chameleon.core` to `dev.hypera.chameleon`. The name `api` makes more sense as the `core` module is mostly just abstract classes and interfaces that are implemented by each platform and the package `dev.hypera.chameleon` generally looks cleaner.

**Comment by Harshvardhantomar** [comment]
I will work on this problem if u have not assigned it to anybody.
