### ISSUE TITLE
UserConnectEvent cannot be cancelled

### ISSUE THREAD

**Issue by GoldenGamerLP** [ChameleonFramework/Chameleon#239]
### Confirmation

- [X] I have checked for similar issues.
- [X] I using the latest version of Chameleon.

### Describe the bug

When canceling the UserConnectEvent, with orn without a reason, the user is not being kicked. 

(Also i saw that the implementation of minestom, the events, are using EventBuilder#ignoredIfCancelled(false);, which devers the purpose of the EventSubscriber#acceptCancelled(true) )

### Expected behaviour

Kicked/Denied the connection/player with a reason.

### Reproduction steps

```Java
public class PlayerLoginEvent implements EventSubscriber<UserConnectEvent> {

   public PlayerLoginEvent(ChameleonPlugin pl) {
      pl.getChameleon().getEventbus().subscribe(this);
   }

   public void on(UserConnectEvent event) throws Exception {
       event.cancel(true);
   }

   @Override
   public boolean acceptCancelled() {
    //Gets ingored in the Minestom Impl
    return true;
   }
}
```

### Exception

```exception
There is no exception.
```

### Environment

```Markdown
Operating System: Windows 11 & Windows 10
Platform(s): Minestom (Latest Release)
```

### Additional information

None

**Comment by joshuasing** [comment]
> (Also i saw that the implementation of minestom, the events, are using EventBuilder#ignoredIfCancelled(false);, which devers the purpose of the EventSubscriber#acceptCancelled(true) )

I thought `EventBuilder#ignoredIfCancelled(false)` meant that it should not ignore cancelled events :thinking:

**Comment by GoldenGamerLP** [comment]
Okay, despite it, the boolean in the EvenSubscriber doesn't get used at all.

**Comment by joshuasing** [comment]
> Okay, despite it, the boolean in the EvenSubscriber doesn't get used at all.

The `acceptsCancelled` boolean is used here: https://github.com/ChameleonFramework/Chameleon/blob/556d96ac8acdca29c092ce065dc0e7a53da5b448/api/src/main/java/dev/hypera/chameleon/event/EventBusImpl.java#LL71C31-L71C31

**Comment by joshuasing** [comment]
Support for Minestom in Chameleon has been discontinued - #268 
Sorry for any inconvenience.
