### ISSUE TITLE
Remove Minestom platform

### ISSUE THREAD

**Issue by LooFifteen** [ChameleonFramework/Chameleon#268]
### Confirmation

- [X] I have checked for similar issues.

### Problem

Due to its artifact management, Minestom has been a pain to upkeep. In addition to this, it is very unlikely that someone is to use Chameleon for a Minestom extension - especially with the recent move to minestom-ce, which doesn't have extensions.

### Suggested solution

We should remove Minestom support altogether as it is unlikely to be used and no longer matches the purpose of Chameleon.

**Comment by joshuasing** [comment]
`minestom-ce` is being pulled back into Minestom: https://github.com/Minestom/Minestom/pull/1937 (marked ready for review September 18, 2023 21:24 UTC).

This pull-back does not remove the extension system, however an opt-in/out-out system may be created.
Additionally the pull-back will introduce publishing to Maven Central and Sonatype.

Maybe it would be worth reverting this change and updating the Minestom platform once this pull request has been merged?
