### ISSUE TITLE
Improve GitHub issue templates

### ISSUE THREAD

**Issue by joshuasing** [ChameleonFramework/Chameleon#292]
### Confirmation

- [X] I have checked for similar issues.

### Problem

The current GitHub issue templates require fields that should not be required, and format most fields as markdown inside code blocks.

### Suggested solution

We should improve the GitHub issue templates, making it easier to report bugs and suggest ideas.

**Comment by gayatriagarwal19** [comment]
Hi, I would like to contribute to this issue, please assign it to me @joshuasing .

**Comment by joshuasing** [comment]
> Hi, I would like to contribute to this issue, please assign it to me @joshuasing .

Done! Thank you for taking the time to contribute!

**Comment by gayatriagarwal19** [comment]
@joshuasing  Do you want any specific improvements ?

**Comment by joshuasing** [comment]
Hi @gayatriagarwal19, sorry for the delay.
The specific improvements that I think would be good are in `bug_report.yml`: making all of the text fields formatted normally and without being in a code block and making "Exception" and "Reproduction steps" not required.
