### ISSUE TITLE
Build and test with Java 21

### ISSUE THREAD

**Issue by joshuasing** [ChameleonFramework/Chameleon#306]
### Confirmation

- [X] I have checked for similar issues.

### Problem

We currently build and test Chameleon with Java 11 and 17.

### Suggested solution

Java 21 is the latest released LTS, so we should be testing with it.
[However, currently Kotlin does not support Java 21 (therefore nor does Gradle).](https://docs.gradle.org/8.4/release-notes.html#:~:text=Currently%2C%20you%20cannot%20run%20Gradle%20on%20Java%2021%20because%20Kotlin%20lacks%20support%20for%20JDK%2021.%20However%2C%20support%20for%20running%20Gradle%20with%20Java%2021%20is%20expected%20in%20future%20versions.)

As soon as Kotlin and Gradle fully support Java 21:
- [ ] Update `gradle.yml`, `release.yml` and `snapshot.yml` to use Java 21
- [x] Update `chameleon.base.gradle.kts` to test with Java 21 (**This can be done before Gradle supports running with Java 21**)

**Comment by aditya4567uk** [comment]
hello there can i contribute in this section , i can compile the code in java 21

**Comment by joshuasing** [comment]
> hello there can i contribute in this section , i can compile the code in java 21 , so can you please assign me this issue?

Hi @aditya4567uk, as noted in the issue:
> [However, currently Kotlin does not support Java 21 (therefore nor does Gradle).](https://docs.gradle.org/8.4/release-notes.html#:~:text=Currently%2C%20you%20cannot%20run%20Gradle%20on%20Java%2021%20because%20Kotlin%20lacks%20support%20for%20JDK%2021.%20However%2C%20support%20for%20running%20Gradle%20with%20Java%2021%20is%20expected%20in%20future%20versions.)

This issue is currently blocked until Kotlin and Gradle both fully support Java 21.

**Comment by joshuasing** [comment]
> hello there can i contribute in this section , i can compile the code in java 21 , so can you please assign me this issue?

Hi @aditya4567uk, a part of this issue can currently be done if you are interested in making a PR:
> Update chameleon.base.gradle.kts to test with Java 21

The other part, using Java 21 in our CI workflows, cannot be done until Gradle and Kotlin support it.

**Comment by joshuasing** [comment]
Hi @aditya4567uk, are you still interested in working on this issue?
If you need any help, feel free to let me know :)
